# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-11-25 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Argument',
            new_name='Args',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='ip_addr',
            new_name='ipaddr',
        ),
    ]
